function h14_eqn = h14_eqn(RHipPitch,RKneePitch)
%H14_EQN
%    H14_EQN = H14_EQN(RHIPPITCH,RKNEEPITCH)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    12-Nov-2017 11:33:37

t2 = conj(RHipPitch);
t3 = cos(t2);
t4 = conj(RKneePitch);
t5 = cos(t4);
t6 = t3.*(2.0./5.0);
t7 = t5.*(8.3e1./2.0e2);
t8 = t6+t7+1.0./1.0e1;
t9 = 1.0./t8;
h14_eqn = [t9.*(t3.*2.587302772907413e2+t5.*2.684326626891441e2-6.15308728319153);t9.*(t3.*1.471180898652705e2+t5.*1.526350182352181e2-sin(t2).*2.841287376523865e2-sin(t4).*2.94783565314351e2+2.967630402500796e1)];
