function h15_eqn = h15_eqn(LHipPitch,LKneePitch)
%H15_EQN
%    H15_EQN = H15_EQN(LHIPPITCH,LKNEEPITCH)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    11-Nov-2017 15:16:54

t2 = conj(LHipPitch);
t3 = cos(t2);
t4 = conj(LKneePitch);
t5 = cos(t4);
t6 = t3.*(2.0./5.0);
t7 = t5.*(7.7e1./5.0);
t8 = t6+t7+1.0./1.0e1;
t9 = 1.0./t8;
h15_eqn = [t9.*(t3.*2.587302772907413e2+t5.*9.96111567569354e3+1.355182259285622e2);t9.*(t3.*1.471180898652705e2+t5.*5.664046459812914e3-sin(t2).*2.841287376523865e2-sin(t4).*1.093895639961688e4+2.967630402500796e1)];
