function h19_eqn = h19_eqn(RHipYaw,RHipPitch,RKneePitch)
%H19_EQN
%    H19_EQN = H19_EQN(RHIPYAW,RHIPPITCH,RKNEEPITCH)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    01-Nov-2017 22:05:21

t2 = sin(RHipPitch);
t3 = sin(RKneePitch);
t4 = cos(RHipYaw);
t5 = sin(RHipYaw);
h19_eqn = [t3.*2.876503282808917e5+t2.*t4.*2.772533284635101e5-6.931333211587753e3;t2.*t5.*2.780138479353805e5+6.950346198384514e4;t3.*2.704893958239888e5+cos(RHipPitch).*4.0e2+cos(RKneePitch).*4.15e2+t2.*t4.*2.607126706737241e5+t2.*t5.*1.259458156345963e5+2.506863714180597e4;0.0];
