function h2_eqn = h2_eqn(bodyZ)
%H2_EQN
%    H2_EQN = H2_EQN(BODYZ)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    07-Nov-2017 23:37:34

h2_eqn = (bodyZ.*(-2.25694405261388e-5)+1.0).^(2.1e1./4.0).*1.01325e3;
