function H2_matrix_eq = H2_matrix(bodyZ)
%H2_MATRIX
%    H2_MATRIX_EQ = H2_MATRIX(BODYZ)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    08-Nov-2017 23:58:14

H2_matrix_eq = [0.0,0.0,(bodyZ.*(-2.25694405261388e-5)+1.0).^(1.7e1./4.0).*(-1.200595494688282e-1),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0];
