function h3_eqn = h3_eqn(bodyX,bodyY,d_bodyX,d_bodyY)
%H3_EQN
%    H3_EQN = H3_EQN(BODYX,BODYY,D_BODYX,D_BODYY)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    08-Nov-2017 23:58:14

h3_eqn = [-bodyX;bodyY;-d_bodyX;d_bodyY];
