function h4_eqn = h4_eqn(RHipYaw,RHipPitch)
%H4_EQN
%    H4_EQN = H4_EQN(RHIPYAW,RHIPPITCH)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    07-Nov-2017 20:02:04

t2 = cos(RHipPitch);
t3 = t2.*(2.0./5.0);
t4 = t3+1.0./1.0e1;
t5 = 1.0./t4;
t6 = sin(RHipPitch);
h4_eqn = [t5.*(t2.*2.587302772907413e2+t6.*sin(RHipYaw).*2.833426264235074e2-6.15308728319153);t5.*(t2.*1.471180898652705e2+t6.*cos(RHipYaw).*2.841287376523865e2+5.808917779024661e1)];
