function h4_eqn = h4_eqn(RHipYaw,RHipPitch)
%H4_EQN
%    H4_EQN = H4_EQN(RHIPYAW,RHIPPITCH)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    02-Nov-2017 13:29:12

t2 = cos(RHipPitch);
t3 = t2.*4.0e2;
t4 = t3+1.0e2;
t5 = 1.0./t4;
t6 = sin(RHipPitch);
h4_eqn = [t5.*(t2.*2.587302772907413e5+t6.*sin(RHipYaw).*2.833426264235074e5-6.15308728319153e3);t5.*(t2.*1.471180898652705e5+t6.*cos(RHipYaw).*2.841287376523865e5+5.808917779024661e4)];
