function h5_eqn = h5_eqn(RHipYaw,RHipPitch)
%H5_EQN
%    H5_EQN = H5_EQN(RHIPYAW,RHIPPITCH)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    01-Nov-2017 22:05:14

t2 = sin(RHipPitch);
t3 = cos(RHipYaw);
t4 = sin(RHipYaw);
h5_eqn = [t2.*t3.*2.833426264235074e5+2.125069698176306e4;t2.*t4.*2.841287376523865e5-7.103218441309662e4;cos(RHipPitch).*4.0e2+t2.*t3.*2.587302772907413e5+t2.*t4.*1.471180898652705e5-1.727475166951202e4;0.0];
