function h6_eqn = h6_eqn(RAnklePitch,RHipYaw,RHipPitch,RKneePitch)
%H6_EQN
%    H6_EQN = H6_EQN(RANKLEPITCH,RHIPYAW,RHIPPITCH,RKNEEPITCH)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    01-Nov-2017 22:05:15

t2 = sin(RHipPitch);
t3 = sin(RAnklePitch);
t4 = sin(RKneePitch);
t5 = cos(RHipYaw);
t6 = sin(RHipYaw);
h6_eqn = [t3.*2.833426264235074e5+t4.*2.833426264235074e5+t2.*t5.*2.833426264235074e5+4.95849596241138e4;t2.*t6.*2.841287376523865e5-7.103218441309662e4;t3.*2.587302772907413e5+t4.*2.587302772907413e5+cos(RAnklePitch).*4.0e2+cos(RHipPitch).*4.0e2+cos(RKneePitch).*4.0e2+t2.*t5.*2.587302772907413e5+t2.*t6.*1.471180898652705e5+8.598276059562104e3;0.0];
