function h7_eqn = h7_eqn(LAnklePitch,LHipYaw,LHipPitch,LKneePitch)
%H7_EQN
%    H7_EQN = H7_EQN(LANKLEPITCH,LHIPYAW,LHIPPITCH,LKNEEPITCH)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    01-Nov-2017 22:05:15

t2 = sin(LHipPitch);
t3 = cos(LAnklePitch);
t4 = sin(LKneePitch);
t5 = cos(LHipYaw);
t6 = sin(LHipYaw);
h7_eqn = [t3.*1.416713132117537e5+t4.*2.833426264235074e5+t2.*t5.*2.833426264235074e5+4.95849596241138e4;t2.*t6.*2.841287376523865e5+7.103218441309662e4;t3.*1.293651386453706e5+t4.*2.587302772907413e5+cos(LHipPitch).*4.0e2+cos(LKneePitch).*4.0e2-sin(LAnklePitch).*2.0e2+t2.*t5.*2.587302772907413e5+t2.*t6.*1.471180898652705e5+8.215732099219735e4;0.0];
