function h7_eqn = h7_eqn(LAnklePitch,LHipPitch,LKneePitch)
%H7_EQN
%    H7_EQN = H7_EQN(LANKLEPITCH,LHIPPITCH,LKNEEPITCH)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    07-Nov-2017 23:37:36

t2 = conj(LHipPitch);
t3 = cos(t2);
t4 = conj(LKneePitch);
t5 = cos(t4);
t6 = conj(LAnklePitch);
t7 = sin(t6);
t8 = t3.*(2.0./5.0);
t9 = t5.*(2.0./5.0);
t10 = t7.*(1.0./5.0);
t11 = t8+t9+t10+1.0./1.0e1;
t12 = 1.0./t11;
h7_eqn = [t12.*(t3.*2.587302772907413e2+t5.*2.587302772907413e2+t7.*1.293651386453706e2+1.355182259285622e2);t12.*(t3.*1.471180898652705e2+t5.*1.471180898652705e2+t7.*7.355904493263524e1+cos(t6).*1.420643688261932e2-sin(t2).*2.841287376523865e2-sin(t4).*2.841287376523865e2+2.967630402500796e1)];
