function tot = generated_mag_rot(Mx,My,Mz,ph1,rh1,th1)
%GENERATED_MAG_ROT
%    TOT = GENERATED_MAG_ROT(MX,MY,MZ,PH1,RH1,TH1)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    14-Sep-2016 13:51:16

t2 = cos(ph1);
t3 = sin(th1);
t4 = cos(th1);
t5 = sin(ph1);
t6 = sin(rh1);
t7 = cos(rh1);
tot = [Mx.*(t2.*t4-t3.*t5.*t6)+Mz.*(t2.*t3+t4.*t5.*t6)-My.*t5.*t7,Mx.*(t4.*t5+t2.*t3.*t6)+Mz.*(t3.*t5-t2.*t4.*t6)+My.*t2.*t7,My.*t6-Mx.*t3.*t7+Mz.*t4.*t7];
