function [H,hx] = generated_H12(l1,l2,ph1,ph2,th1,th2)
%GENERATED_H12
%    [H,HX] = GENERATED_H12(L1,L2,PH1,PH2,TH1,TH2)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    13-Sep-2016 11:58:29

t2 = sin(ph1);
t3 = sin(th1);
t4 = cos(ph1);
t5 = cos(th1);
t6 = sin(ph2);
t7 = sin(th2);
t8 = l1.*t4.*t5;
t9 = cos(ph2);
t10 = cos(th2);
t11 = l2.*t9.*t10;
H = reshape([-l1.*t3.*t4,-l1.*t2.*t3,-l1.*t5,-l1.*t3.*t4,-l1.*t2.*t3,-l1.*t5,0.0,0.0,0.0,-l2.*t7.*t9,-l2.*t6.*t7,-l2.*t10,0.0,0.0,0.0,0.0,0.0,0.0,-l1.*t2.*t5,t8,0.0,-l1.*t2.*t5,t8,0.0,0.0,0.0,0.0,-l2.*t6.*t10,t11,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[6,6]);
if nargout > 1
    t12 = l1.*t2.*t5;
    hx = [t8;t12;-l1.*t3;t8+t11;t12+l2.*t6.*t10;-l1.*t3-l2.*t7];
end
