function [H,hx] = generated_H3(l1,l2,l3,ph1,ph2,ph3,th1,th2,th3)
%GENERATED_H3
%    [H,HX] = GENERATED_H3(L1,L2,L3,PH1,PH2,PH3,TH1,TH2,TH3)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    13-Sep-2016 12:02:34

t2 = sin(ph1);
t3 = sin(th1);
t4 = sin(ph2);
t5 = sin(th2);
t6 = sin(ph3);
t7 = sin(th3);
t8 = cos(ph1);
t9 = cos(th1);
t10 = cos(ph2);
t11 = cos(th2);
t12 = cos(ph3);
t13 = cos(th3);
t14 = l1.*t8.*t9;
t15 = l2.*t10.*t11;
t16 = l3.*t12.*t13;
H = reshape([-l1.*t3.*t8,-l1.*t2.*t3,-l1.*t9,-l2.*t5.*t10,-l2.*t4.*t5,-l2.*t11,-l3.*t7.*t12,-l3.*t6.*t7,-l3.*t13,-l1.*t2.*t9,t14,0.0,-l2.*t4.*t11,t15,0.0,-l3.*t6.*t13,t16,0.0],[3,6]);
if nargout > 1
    hx = [t14+t15+t16;l1.*t2.*t9+l2.*t4.*t11+l3.*t6.*t13;-l1.*t3-l2.*t5-l3.*t7];
end
