function [H,hx] = generated_H13(l1,l2,l3,ph1,ph2,ph3,th1,th2,th3)
%GENERATED_H13
%    [H,HX] = GENERATED_H13(L1,L2,L3,PH1,PH2,PH3,TH1,TH2,TH3)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    13-Sep-2016 12:03:11

t2 = sin(ph1);
t3 = sin(th1);
t4 = cos(ph1);
t5 = cos(th1);
t6 = sin(ph2);
t7 = sin(th2);
t8 = sin(ph3);
t9 = sin(th3);
t10 = l1.*t4.*t5;
t11 = cos(ph2);
t12 = cos(th2);
t13 = cos(ph3);
t14 = cos(th3);
t15 = l2.*t11.*t12;
t16 = l3.*t13.*t14;
H = reshape([-l1.*t3.*t4,-l1.*t2.*t3,-l1.*t5,-l1.*t3.*t4,-l1.*t2.*t3,-l1.*t5,0.0,0.0,0.0,-l2.*t7.*t11,-l2.*t6.*t7,-l2.*t12,0.0,0.0,0.0,-l3.*t9.*t13,-l3.*t8.*t9,-l3.*t14,-l1.*t2.*t5,t10,0.0,-l1.*t2.*t5,t10,0.0,0.0,0.0,0.0,-l2.*t6.*t12,t15,0.0,0.0,0.0,0.0,-l3.*t8.*t14,t16,0.0],[6,6]);
if nargout > 1
    t17 = l1.*t2.*t5;
    hx = [t10;t17;-l1.*t3;t10+t15+t16;t17+l2.*t6.*t12+l3.*t8.*t14;-l1.*t3-l2.*t7-l3.*t9];
end
