function [H,hx] = generated_H2(l1,l2,ph1,ph2,th1,th2)
%GENERATED_H2
%    [H,HX] = GENERATED_H2(L1,L2,PH1,PH2,TH1,TH2)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    13-Sep-2016 12:02:51

t2 = sin(ph1);
t3 = sin(th1);
t4 = sin(ph2);
t5 = sin(th2);
t6 = cos(ph1);
t7 = cos(th1);
t8 = cos(ph2);
t9 = cos(th2);
t10 = l1.*t6.*t7;
t11 = l2.*t8.*t9;
H = reshape([-l1.*t3.*t6,-l1.*t2.*t3,-l1.*t7,-l2.*t5.*t8,-l2.*t4.*t5,-l2.*t9,0.0,0.0,0.0,-l1.*t2.*t7,t10,0.0,-l2.*t4.*t9,t11,0.0,0.0,0.0,0.0],[3,6]);
if nargout > 1
    hx = [t10+t11;l1.*t2.*t7+l2.*t4.*t9;-l1.*t3-l2.*t5];
end
