function [H,hx] = generated_H23(l1,l2,l3,ph1,ph2,ph3,th1,th2,th3)
%GENERATED_H23
%    [H,HX] = GENERATED_H23(L1,L2,L3,PH1,PH2,PH3,TH1,TH2,TH3)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    13-Sep-2016 11:59:30

t2 = sin(ph1);
t3 = sin(th1);
t4 = sin(ph2);
t5 = sin(th2);
t6 = cos(ph1);
t7 = cos(th1);
t8 = cos(ph2);
t9 = cos(th2);
t10 = sin(ph3);
t11 = sin(th3);
t12 = l1.*t6.*t7;
t13 = l2.*t8.*t9;
t14 = cos(ph3);
t15 = cos(th3);
t16 = l3.*t14.*t15;
H = reshape([-l1.*t3.*t6,-l1.*t2.*t3,-l1.*t7,-l1.*t3.*t6,-l1.*t2.*t3,-l1.*t7,-l2.*t5.*t8,-l2.*t4.*t5,-l2.*t9,-l2.*t5.*t8,-l2.*t4.*t5,-l2.*t9,0.0,0.0,0.0,-l3.*t11.*t14,-l3.*t10.*t11,-l3.*t15,-l1.*t2.*t7,t12,0.0,-l1.*t2.*t7,t12,0.0,-l2.*t4.*t9,t13,0.0,-l2.*t4.*t9,t13,0.0,0.0,0.0,0.0,-l3.*t10.*t15,t16,0.0],[6,6]);
if nargout > 1
    t17 = l1.*t2.*t7;
    t18 = l2.*t4.*t9;
    hx = [t12+t13;t17+t18;-l1.*t3-l2.*t5;t12+t13+t16;t17+t18+l3.*t10.*t15;-l1.*t3-l2.*t5-l3.*t11];
end
