function tot = generated_acc_rot(Ax,Ay,Az,ph1,rh1,th1)
%GENERATED_ACC_ROT
%    TOT = GENERATED_ACC_ROT(AX,AY,AZ,PH1,RH1,TH1)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    14-Sep-2016 10:07:28

t2 = cos(ph1);
t3 = sin(th1);
t4 = cos(th1);
t5 = sin(ph1);
t6 = sin(rh1);
t7 = cos(rh1);
tot = [Ax.*(t2.*t4-t3.*t5.*t6)+Az.*(t2.*t3+t4.*t5.*t6)-Ay.*t5.*t7;Ax.*(t4.*t5+t2.*t3.*t6)+Az.*(t3.*t5-t2.*t4.*t6)+Ay.*t2.*t7;Ay.*t6-Ax.*t3.*t7+Az.*t4.*t7];
